---
- name: Install ZFS
  ansible.builtin.apt:
    name:
      - zfsutils-linux
    state: present

- name: Create ZFS auto key loading service
  ansible.builtin.template:
    src: zfs-load-key.service.j2
    dest: /etc/systemd/system/zfs-load-key.service
    mode: 0644

- name: Enable ZFS mount service for automatic mounting at boot
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - zfs-mount
    - zfs-import-cache
    - zfs-load-key
