---
- name: Install packages to auto-detect the distribution
  apt:
    name:
      - lsb-release
    state: latest
  register: lsb_installed

- name: Store the distribution codename used as a full command output
  command:
    cmd: lsb_release -cs
  register: distribution_codename

- name: Store the distribution codename used as a full command output
  command:
    cmd: dpkg --print-architecture
  register: system_architecture

- name: Set variable for the playbook
  set_fact:
    distribution_codename: "{{ distribution_codename.stdout }}" # Keeping only the stdout as one line of the command rather than full ansible output
    system_architecture: "{{ system_architecture.stdout }}"
    source_url: http://deb.debian.org/debian

- name: Add debian-backports apt repository
  apt_repository:
    repo: deb {{ source_url }} {{ distribution_codename }}-backports main contrib
    filename: "{{ distribution_codename }}-backports"

- name: Add debian-backports apt repository
  apt_repository:
    repo: deb-src {{ source_url }} {{ distribution_codename }}-backports main contrib
    filename: "{{ distribution_codename }}-backports"

- name: Install ZFS dependencies
  apt:
    name:
      - linux-headers-{{ system_architecture }}
    state: latest

- name: Install ZFS
  apt:
    name:
      - zfsutils-linux
    default_release: "{{ distribution_codename }}-backports"
    state: latest
  notify: Reboot

- name: Enable ZFS mount service for automatic mounting at boot
  service:
    name: zfs-mount
    state: started
    enabled: true

- name: Enable ZFS import service for automatic importing at boot
  service:
    name: zfs-import-cache
    state: started
    enabled: true

- name: Create ZFS auto key loading service
  template:
    src: zfs-load-key.service.j2
    dest: /etc/systemd/system/zfs-load-key.service
  register: key_loading_service_added

- name: Enable ZFS mount service for automatic mounting at boot
  service:
    name: zfs-load-key.service
    state: started
    enabled: true
  when: key_loading_service_added.changed
