---
- name: Staging server
  hosts: staging

  handlers:
    - name: Handlers
      ansible.builtin.import_tasks: handlers/main.yml

  roles:
    - role: samba
    - role: dyndns
    - role: nextcloud
