---
- name: Production server
  hosts: production

  handlers:
    - name: Handlers
      ansible.builtin.import_tasks: handlers/main.yml

  roles:
    - role: samba
    - role: dyndns
    - role: nextcloud
