---
- name: Production server
  hosts: production

  handlers:
    - name: Handlers
      ansible.builtin.import_tasks: handlers/main.yml

  roles:
    - role: dropbear
    - role: system
    - role: hostname
    - role: geerlingguy.security
    - role: unatended_upgrades
    - role: chriswayg.msmtp-mailer
    - role: docker
    - role: zfs
