---
- name: Production server
  hosts: production

  handlers:
    - name: Handlers
      ansible.builtin.import_tasks: handlers/main.yml

  roles:
    - role: dropbear
    - role: system
    - role: hostname
    - role: ssh
    - role: unatended_upgrades
    - role: docker
    - role: zfs
