- name: Remove un-needed packages
  apt:
    name: "{{ packages_to_remove }}"
    state: absent
    purge: yes

- name: Install essential packages
  apt:
    name: "{{ packages_to_install }}"
    state: latest

- name: Change hostname
  hostname:
    name: "{{ hostname }}"

- name: Disable SSH password auth
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
  register: sshd_config

- name: Enable passwordless sudo for "{{ username }}"
  lineinfile:
    path: /etc/sudoers
    regexp: "^%sudo"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: restart SSH daemon
  service:
    name: sshd
    enabled: yes
    state: restarted
  when: sshd_config.changed

- name: Disable suspend when lid is closed
  lineinfile:
    path: /etc/systemd/logind.conf
    regexp: "^HandleLidSwitch"
    line: "HandleLidSwitch=ignore"
