- name: Update apt packages
  apt:
    update_cache: yes
    upgrade: full
    autoclean: yes
    autoremove: yes

- name: Check if reboot is needed
  stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Reboot if required
  reboot:
  when: reboot_required.stat.exists
