---
- name: Install Samba
  ansible.builtin.apt:
    name:
      - samba
    state: present

- name: Create samba folder
  ansible.builtin.file:
    path: "{{ samba_share_path }}"
    state: directory
    mode: 0755 # Giving read/write access to groups and all to access as guest
    owner: nobody
    group: nogroup

- name: Adding the configuration for the share
  ansible.builtin.blockinfile:
    path: /etc/samba/smb.conf
    insertafter:
    block: |
      [nas]
      path = {{ samba_share_path }}
      guest only = yes
      public = yes
      read only = no
    backup: true
  notify: Restart smbd service

- name: Allow all handlers to run
  ansible.builtin.meta: flush_handlers
