---
- name: Install dyndns nescessary package
  ansible.builtin.apt:
    name:
      - curl
    state: present

- name: Add template script file for DynDNS support
  ansible.builtin.template:
    src: dyndns_nextcloud.sh.j2
    dest: /usr/local/sbin/dyndns_nextcloud.sh
    mode: 0644

- name: Add a cron job to automatically update the DyNDNS IP address
  ansible.builtin.cron:
    job: bash /usr/local/sbin/dyndns_nextcloud.sh
    # Will run every day at 00:00:00
    hour: 0
    minute: 0
    name: Update the DyNDNS IP address
