---
- name: Install dyndns nescessary package
  apt:
    name:
      - curl
    state: latest

- name: Add template script file for Dyn DNS support
  template:
    src: dyndns_nextcloud.sh.j2
    dest: /usr/local/bin/dyndns_nextcloud.sh
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Add a cron job to automatically update the DyNDNS IP address
  cron:
    job: "bash /usr/local/bin/dyndns_nextcloud.sh"
    hour: "0" # Will run every day at 00:00:00
    minute: "0"
    name: "Update the DyNDNS IP address"
    user: "{{ username }}"
