---
- name: Reboot
  ansible.builtin.reboot:
  when: reboot_required.stat.exists

- name: Restart docker service
  ansible.builtin.service:
    name: docker
    state: restarted
    enabled: true

- name: Restart smbd service
  ansible.builtin.service:
    name: smbd
    state: restarted
    enabled: true

- name: Restart caddy container
  community.docker.docker_container:
    name: caddy
    restart: true
    container_default_behavior: no_defaults
  when: caddy_container.exists

- name: Rebuild initramfs
  ansible.builtin.command: update-initramfs -u
