---
- name: Create build directory for the custom nextcloud image
  ansible.builtin.file:
    path: "{{ docker_volumes_root }}"
    state: directory
    mode: 0755

- name: Create a docker network for nextcloud related services
  community.docker.docker_network:
    name: nextcloud

- name: Postgres docker setup
  ansible.builtin.include_tasks: postgres.yml

- name: Redis docker setup
  ansible.builtin.include_tasks: redis.yml

- name: Nextcloud docker setup
  ansible.builtin.include_tasks: nextcloud.yml

- name: Caddy docker setup
  ansible.builtin.include_tasks: caddy.yml
