---
- name: Install aptitude
  ansible.builtin.apt:
    name: aptitude
    state: present

- name: Update apt packages
  ansible.builtin.apt:
    upgrade: full
    update_cache: true
    autoclean: true
    autoremove: true

- name: Check if reboot is needed
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Disable suspend when lid is closed
  ansible.builtin.lineinfile:
    path: /etc/systemd/logind.conf
    regexp: ^HandleLidSwitch
    line: HandleLidSwitch=ignore

- name: Disable cron e-mail notifications
  cron:
    name: MAILTO
    user: root
    env: yes
    job: ""

- name: Allow all handlers to run
  ansible.builtin.meta: flush_handlers
