---
- name: Update apt packages
  ansible.builtin.apt:
    upgrade: full
    update_cache: true
    autoclean: true
    autoremove: true

- name: Check if reboot is needed
  ansible.builtin.stat:
    path: /var/run/reboot-required
  notify: Reboot

- name: Reboot if required
  ansible.builtin.reboot:
  when: reboot_required.stat.exists

- name: Enable passwordless sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: ^%sudo
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: /usr/sbin/visudo -cf %s

- name: Disable suspend when lid is closed
  ansible.builtin.lineinfile:
    path: /etc/systemd/logind.conf
    regexp: ^HandleLidSwitch
    line: HandleLidSwitch=ignore

- name: Allow all handlers to run
  ansible.builtin.meta: flush_handlers
